language: cpp
dist: xenial

addons:
  apt:
    packages: cmake
  homebrew:
    packages: cmake glib

matrix:
  allow_failures:
  - os: osx

before_script:
 - mkdir build && cd build
 - cmake .. $(cmake_options)

script:
 - make

jobs:
  include:
## Builds with only one feature enables
    - stage: "Basic builds"
      name: "Linux GCC"
    - name: "Linux Clang"
      compiler: clang
    - name: "macOS GCC"
      os: osx

## Builds with only one feature enables
    - stage: "Partial Linux GCC builds"
      name: "Release"
      cmake_options: "-DCMAKE_BUILD_TYPE=Release"
    - name: "Static"
      cmake_options: "-DBUILD_STATIC=on"
    - name: "Lenstool"
      cmake_options: "-DBUILD_LENSTOOL=on"
    - name: "Doc"
      cmake_options: "-DBUILD_DOC=on"


## Builds with all features enabled
    - stage: "Full builds"
      name: "Linux GCC"
      cmake_options: "-DCMAKE_BUILD_TYPE=Release -DBUILD_LENSTOOL=on -DBUILD_DOC=on"
    - name: "Linux GCC static"
      cmake_options: "-DCMAKE_BUILD_TYPE=Release -DBUILD_LENSTOOL=on -DBUILD_DOC=on -DBUILD_STATIC=on"
    - name: "Linux Clang"
      compiler: clang
      cmake_options: "-DCMAKE_BUILD_TYPE=Release -DBUILD_LENSTOOL=on -DBUILD_DOC=on"
    - name: "macOS GCC"
      os: osx
      cmake_options: "-DCMAKE_BUILD_TYPE=Release -DBUILD_LENSTOOL=on -DBUILD_DOC=on"

    - stage: test
      name: "Linux GCC"
      cmake_options: "-DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=on"
      script:
       - make
       - make test
