language: cpp
dist: xenial

addons:
  apt:
    packages:
     - cmake

script:
 - mkdir build && cd build
 - cmake ..
 - make

jobs:
  include:
    - name: "Linux GCC"
    - name: "Linux Clang"
      compiler: clang
    - name: "macOS GCC"
      os: osx
